name: Hello World! 2024

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World! 2024"
       - name: Now it is
        run: |
          date %A %B %F
       - name: Directory content
        run: |
          ls -A